version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  # webサーバーと同階層
  db:
    build: ./infra/mysql
    hostname: cake-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cake-app-DB 
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: